name: 'Mailgun'
author: 'Vineet Choudhary'
description: 'Github action to send a mail using the Mailgun API'
branding:
    icon: 'mail'
    color: 'red'
inputs:
    api-key:
        description: 'Mailgun API Key'
        required: true
    domain:
        description: 'Your Domain Name'
        required: true
    to:
        description: 'Email address of the recipient(s). Example: bob@host.com. You can use commas to separate multiple recipients.'
        required: true
    from:
        description: 'The email that will be shown as sender'
        required: false
    subject:
        description: 'Email subject. Following custom placeholders that can be used - $EVENT$, $ISSUE$, $ACTION$'
        required: false
        default: 'GitHub action notification - $ACTION$'
    body:
        description: 'Body of the email (HTML Supported). Following custom placeholders that can be used - $EVENT$, $ISSUE$, $ACTION$'
        required: false
        default: 'The following action $ACTION$ produced an event $EVENT$'
runs:
    using: 'node12'
    main: 'dist/index.js'