name: On Push Email

on: [push]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    name: Send email on every push
    steps:
    - uses: vineetchoudhary/Mailgun@master
      id: sendmail
      name: Send Mail Action
      with:
        api-key: ${{ secrets.API_KEY }}
        domain: ${{ secrets.DOMAIN }}
        to: vineetchoudhary@live.in
