name: On Push Email

on: [push]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    name: Send email on every push
    steps:
    - name: Send Mail Action
      id: sendmail
      uses: vineetchoudhary/Mailgun@master
      with:
        api-key: ${{ secrets.API_KEY }}
        domain: ${{ secrets.DOMAIN }}
        to: ${{ secrets.TO }}
    - name: Send Mail Action Response
      run: echo "${{ steps.sendmail.outputs.response }}"
